### PR TITLE
meter element and styles for password strength functionality

### PR DESCRIPTION
**Pull request by jalbertbowden**
[issue: #216](https://github.com/openva/richmondsunlight.com/issues/216)

### CODE REVIEW

**Comment by waldoj** [comment]
Thanks for this fix, @jalbertbowden! I'm so glad I finally have a proper Docker environment for this so that I could easily see what it would do before merging to master or staging. :)

**Comment by jalbertbowden** [comment]
thank you. i'm just happy to finally be able to contribute something. this is going to be fun.

**Comment by jalbertbowden** [comment]
how should i keep my fork up to date? or rather, how would you go about doing that? [this is where i go confused last time](https://github.com/KirstieJane/STEMMRoleModels/wiki/Syncing-your-fork-to-the-original-repository-via-the-browser)

**Comment by waldoj** [comment]
Personally, I don’t bother to keep forks up to date. After my PR is accepted (or not!), I delete my fork. Then I create a new one the next time I have a PR to propose.

**Pull request merged**
